# Параметры для поиска вакансий
# Все указанные параметры работают вместе, что может приводить к отсутствию результатов.
# Если надо исключить какой-либо параметр (использовать значение по умолчанию), поставьте перед ним символ комментария #. 

# Подробнее о языке запросов (поле text) здесь: https://hh.ru/article/1175

query:
  text: "Python"
  excluded_text: "senior"  # какие слова исключить из поиска

  # Область поиска, допустимы значения [name, company_name, description]
  search_field: "name"  

  # Регионы, полный список здесь: https://api.hh.ru/areas/
  area: ["2"]  # 1 = Москва, 2 = Санкт-Петербург, 113 = Россия

  # Специализации, полный список здесь: https://api.hh.ru/professional_roles/
  professional_role: ["96"]  # 96 = Программист, разработчик, 165 - Дата-сайентист

  # Уровень дохода
  salary: 120000  # минимальная зарплата (до вычета налогов)
  only_with_salary: true  # только вакансии, где указана зарплата

  # Опыт работы, допустимые значения [no, between1And3, between3And6, moreThan6]
  experience: ["between1And3", "between3And6"]

  per_page: 50  # сколько выдывать вакансий на страницу (максимум 100)
  order_by: "publication_time"  # упорядочить вывод по дате публикации
  label: "not_from_agency"  # исключить объявления от кадровых агентств


general:
  num_workers: 3
  save_results_to_csv: true
  save_results_to_json: true
